# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8090
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
    servlet:
       multipart:
          enabled: true
          max-file-size: 5MB
          max-request-size: 10MB
    # 数据源配置
    datasource:
        # 连接池类型
        type: com.alibaba.druid.pool.DruidDataSource
        # Mysql数据库驱动
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
        #修改数据库连接配置 todo
            url: jdbc:mysql://localhost:3306/uploads?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
            username: root
            password: rootroot
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
    # 服务模块
    devtools:
      restart:
        # 热部署开关
        enabled: true
        
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: cn.fastloader.web.**.model
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
   
# 上传文件存储路径(windows 路径例如:C:/temp/uploadFiles)  todo
prop:
   upload-folder: /Users/zanezhang/uploadFiles
        

